server:
  port: 8761   # Eureka server default port

spring:
  application:
    name: discovery-server

eureka:
  client:
    register-with-eureka: false   # Don't register itself
    fetch-registry: false         # It is the registry, no need to fetch
