server:
  port: 8080   # Gateway runs on 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # User Service
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        # Plan Service
        - id: plan-service
          uri: lb://PLAN-SERVICE
          predicates:
            - Path=/plans/**

        # Payment Service
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**

        # Notification Service
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/**

        # Subscription Audit Service
        - id: subscription-audit-service
          uri: lb://SUBSCRIPTION-AUDIT-SERVICE
          predicates:
            - Path=/audits/**
